bl/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('employees/', include('employees.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

employees/urls.py
from django.urls import path
from . import views
from bl import settings
from django.conf.urls.static import static


app_name = "employees"

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.employees_list, name='list'),
    path('list/search/', views.list_filtered, name='list_filtered'),
    path('detail/<int:detail>', views.employee_detail, name='detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from bl import settings
from django.conf.urls.static import static

app_name = "news"

urlpatterns = [
    path('list', views.news_list, name='list'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl/models.py
from django.db import models

# Create your models here.

employees/models.py
from django.db import models
from django.core.validators import RegexValidator
import uuid
import os

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    path_exd = instance.tabnumber
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join("avatars", path_exd, filename)

class EmployeeExtended(models.Model):
    tabnumber = models.CharField(max_length=14)
    avatar = models.ImageField(upload_to=get_file_path)
    fb_link = models.URLField(max_length=250, blank=True, default='https://www.facebook.com/')
    linkedin_link = models.URLField(max_length=250, blank=True, default='https://www.linkedin.com/')
    instagram_link = models.URLField(max_length=250, blank=True, default='https://www.instagram.com/')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Телефонний номер має бути введений у форматі: '+380999999999'.")
    mobilephone_number = models.CharField(validators=[phone_regex], max_length=13, blank=True)

    class Meta:
        ordering = ('tabnumber',)
        verbose_name = 'EmployeeExtended'
        verbose_name_plural = 'EmployeesExtended'

    def __str__(self):
        return self.tabnumber

news/models.py
from django.db import models

bl/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render


def home(request):
    template_name = 'home_page.html'
    return render(request, template_name, {
        })

employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .services import get_employees_list, get_employees, get_employee, get_employees_detail, get_departments_list, get_employees_filtered_list


def index(request):
    return HttpResponse("Список працівників")


def employee_detail(request, detail):
    template_name = 'employee_detail.html'
    return render(request, template_name, {
            'employee': get_employees_detail(detail)
        })

def list_filtered(request):
    template_name = 'employees_list.html'
    query_dict = (request.GET)
    print(query_dict)
    search_query = query_dict.get("full_name")
    division_id = query_dict.get("division_id")
    return render(request, template_name, {
            'employees': get_employees_filtered_list(search_query, division_id),
            'employees_extended': get_employees(),
            'departments': get_departments_list()
        })


def employees_list(request):
    template_name = 'employees_list.html'
    return render(request, template_name, {
            'employees': get_employees_list(),
            'employees_extended': get_employees(),
            'departments': get_departments_list()
        })

news/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render


def news_list(request):
    template_name = 'news_list.html'
    return render(request, template_name, {})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bank Lviv{% endblock%}</title>
    <script src=" {% static 'js_scripts/script.js' %}" rel="text/javascript" ></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href=" {% static 'css/style.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/style_table.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/style_employee_detail.css' %}" rel="stylesheet" />
    <link rel="icon" href="https://www.banklviv.com/wp-content/themes/banklviv/img/favicon.ico"/>
</head>
<body>
<div class="area">

<nav class="main-menu">
            <ul>
                <li>
                    <a href="/">
                        <div class="fa fa-2x"><img src={% static 'images/index.jpg' %}/></div>
                        <span class="nav-text">
                            Головна
                        </span>
                    </a>

                </li>
                <li class="has-subnav">
                    <a href={% url 'news:list' %}>
                        <i class="fa fa-regular fa-newspaper fa-2x"></i>
                        <div class="nav-text">
                            Новини
                        </div>
                    </a>

                </li>
                <li class="has-subnav">
                    <a href={% url 'employees:list' %}>
                       <i class="fa fa-users fa-2x"></i>
                        <span class="nav-text">
                            Працівники
                        </span>
                    </a>

                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-solid fa-circle-info fa-2x"></i>
                        <span class="nav-text">
                            Про нас
                        </span>
                    </a>

                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-link fa-2x"></i>
                        <span class="nav-text">
                            Корисні посилання
                        </span>
                    </a>
                </li>
            </ul>

            <ul class="logout">
                <li>
                   <a href="#">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Вийти
                        </span>
                    </a>
                </li>
            </ul>
        </nav>
</div>
<div class="wp-content">
  <div class="container-fluid">
    {% block home_page %}
    {% endblock %}
    {% block list %}
        {% block detail %}
        {% endblock detail%}
    {% endblock %}
    {% block news %}
    {% endblock %}
  </div>
</div>
</body>
</html>

templates/employee_detail.html
{% extends "base.html" %}
{% load static %}


{% block detail %}
    <div class="empl_detail_container">
        <div class="empl_card">
            <div class="avatar_container">
                <div class="avatar_big">

                        <img alt="avatar" src="{% static '' %}avatars/default_avatar.png" >

                </div>
            </div>
            <div class="main_info">
                <div class="main_text">{{ employee.first_name }} {{ employee.last_name }}</div>
                <div class="position_text"> {{ employee.position_name }} </div>
                <div class="devision_text"> {{ employee.division_name }} </div>
            </div>
            <div class="social_media">
                <div class="social_media_icon">
                    <a href='#' target="_blank">
                        <i class="fa-2x fa fa-brands fa-facebook-square"></i>
                    </a>
                </div>
                <div class="social_media_icon">
                    <a href="#" target="_blank">
                        <i class="fa-2x fa fa-brands fa-linkedin"></i>
                    </a>
                </div>
                <div class="social_media_icon">
                    <a href="#" target="_blank">
                        <i class="fa-2x fa fa-brands fa-instagram-square"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="btn_container">
            <button class="btn">
                <a href="{% url 'employees:list' %}">до переліку</a>
            </button>
        </div>
    </div>
{% endblock %}

templates/employees_list.html
{% extends "base.html" %}
{% load static %}

{% block list %}
    <div class="search_form_container">
    <form class="search_form" id="search_form" action="{% url 'employees:list' %}search/" onsubmit="prev_def()">
        <label for="search_empl_field">П.І.Б.</label>
        <input type="text" class="search_empl_field" id="search_empl_field" name="full_name" placeholder="&#xf002">
        <label for="query_dept">підрозділ</label>
        <select name="division_id" id="query_dept" class="query_dept_container">
            <option>обрати із списку ...</option>
            {% for department in departments %}
                <option class="query_dept_field" id='{{ department.id }}' value={{ department.id }}>{{ department.name }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="пошук" class="search-btn"/>
    </form>
    </div>
    <div class="table_container">
<table class="table ">
    <thead>
    <tr>
        <th>Фото</th>
        <th>П.І.Б.</th>
        <th>Підрозділ</th>
        <th>Посада</th>
        <th>Телефон</th>
    </tr>
    </thead>
    <tbody>
    {% for employee in employees %}
    <tr onclick=window.location='http://127.0.0.1:8000/employees/detail/{{ employee.id }}'>
        <td class="avatar">
            {% for employee_extended in employees_extended %}
                {% if employee_extended.tabnumber == employee.tab_no %}
                    {% if employee_extended.avatar %}
                        <img alt="avatar" src="{% static '' %}{{ employee_extended.avatar }}" >
                    {% else %}
                        <img alt="avatar" src="{% static '' %}avatars/default_avatar.png" >
                    {% endif %}
                {% endif %}
            {% endfor %}
        </td>
        <td>{{ employee.last_name }} {{ employee.first_name }} {{ employee.middle_name }}</td>
        <td>{{ employee.division_name }}</td>
        <td>{{ employee.position_name }}</td>
        <td>{% for employee_extended in employees_extended %}
            {% if employee_extended.tabnumber == employee.tab_no %}
                {{ employee_extended.mobilephone_number }}
            {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    </div>
{% endblock %}

templates/home_page.html
{% extends "base.html" %}

{% block home_page %}
    <div>
        <h1>Home page</h1>
    </div>
{% endblock %}

templates/news_list.html
{% extends "base.html" %}

{% block news %}
    <div>
    <h1>News</h1>
    </div>
{% endblock %}